name: release_cli
description: 'A comprehensive CLI tool for streamlining the release process of mobile and web applications across multiple platforms.'
version: 1.1.1
repository: https://github.com/NickBalnaves/release_cli

environment:
  sdk: ^3.5.3

executables:
  release_cli:

dependencies:
  args: ^2.7.0
  crypto: ^3.0.6
  dart_jsonwebtoken: ^2.14.0
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  http: ^1.3.0
  xml: ^6.5.0

dev_dependencies:
  all_lint_rules_community: ^0.0.43
